### ISSUE TITLE
Does user support variables? 

### ISSUE THREAD

**Issue by technicalpickles** [moekidev/jumon#3]
For example:

```
config:
  model: gpt-3.5-turbo-16k
  temperature: 0.7
prompts:
  system:
    subject: Your personality is {{personality}}, your purpose is to {{purpose}}
    variables:
      - name: personality
        patterns:
          - extroverted
          - introverted
      - name: purpose
        patterns:
          - help the user
          - rebel against the user
  user:
    subject: I want to drink delicious coffee
    variables:
      - name: taste
        patterns:
          - strong
          - weak
          - bright
          - tasty
          - yummy
```
